# Generated by Django 6.0.5 on 2026-05-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="extensions/icons/"
            ),
        ),
    ]
